services:
  - type: web
    name: saud-alghamdi-portfolio
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
